apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: reactnative1-ingress
spec:
  rules:
    - host: reactnative1-testreactnative-dev.empcbr.thoughtworks-labs.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: reactnative1
                port: 
                  number: 80
  tls:
  - hosts:
    - reactnative1-testreactnative-dev.empcbr.thoughtworks-labs.net
    secretName: letencryptkey
---
apiVersion: v1
kind: Service
metadata:
  name: reactnative1
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: reactnative1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactnative1
  labels:
    app: reactnative1
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 5
      maxUnavailable: 0
  selector:
    matchLabels:
      app: reactnative1
  template:
    metadata:
      labels:
        app: reactnative1
    spec:
      containers:
      - name: reactnative1
        image: 626109959667.dkr.ecr.us-east-1.amazonaws.com/reactnative1:{image-tag}
        ports:
        - containerPort: 80